name: Take screenshot
on:
  - push
env:
  output: 'asd'

jobs:
  screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Screenshot Capture
        uses: lauta-dev/website-screenshot-capture-action@main
        with:
          url: https://google.com
          name: n
          type: webp
          quality: 40
          output: ${{ output }}
      - name: ls
        run: ls

      - name: ls Screenshots
        run: ls $output
