name: Take screenshot
on:
  - push

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Screenshot Capture
        uses: lauta-dev/website-screenshot-capture-action@re
        with:
          pages_file: pages.yml
          type: webp
          quality: 40
      - name: ls
        run: ls

      - name: ls Screenshots
        run: ls screenshots
