name: Take screenshot
on:
  - push
env:
  output: 'asd'

jobs:
  screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Screenshot Capture
        uses: lauta-dev/website-screenshot-capture-action@load_js_script
        with:
          urls_input_file: pages.yml
          output_dir: n
      - name: ls
        run: ls

      - name: ls Screenshots
        run: ls n

      
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: n

  deploy:
    needs: screenshots
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        run: git clone https://github.com/Lauta-dev/test-action.git .
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: screenshots
          path: screenshots


      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Lauta-dev/test-action.git

      - name: Create screenshot image
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"

      - name: Guardar captura
        run: |
          git push origin main
