name: Take screenshot
on:
  - push

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Screenshot Capture
        uses: lauta-dev/website-screenshot-capture-action@main
        with:
          pages_file: pages.yml
          type: webp
          quality: 40
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/

  remove-metadata:
    runs-on: ubuntu-latest
    needs: [screenshots]
    steps:
      - name: install cwebp
        run: sudo apt-get install webp
      
      - name: Create content
        run: mkdir webp

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: screenshots

      - name: remove meta
        run: |
            for f in *.png; do
              cwebp "$f" -o "webp/$f"
            done

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: webp/
          name: screenshots-without-meta


  push-images:
    runs-on: ubuntu-latest
    needs: [remove-metadata]
    steps:
      - name: Clone repository
        run: git clone https://github.com/Lauta-dev/resource.git .

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: screenshots-without-meta

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.GH_USERNAME }}"
          git config user.email "${{ secrets.GH_MAIL }}"
          git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/Lauta-dev/resource.git

      - name: Add images and commited
        run: |
          git add .
          git commit -m "Agregar captura de pantalla"

      - name: Push screenshots
        run: |
          git push origin main

